name: MyTest

on:
  push:
    branches:
      - main


jobs:
  job1: 
    name: test job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        env:
          ENV: develop
        uses: actions/checkout@v1
        run: |
          node ./ci/test.js
