name: MyTest

on:
  push:
    branches:
      - main

jobs:
  Clone Code: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  Exec Process:
    need: [Clone Code]
    runs-on: ubuntu-latest 
    steps:
      - run: |
          node ./ci/test.js
        
